services:
  sonata.admin.azurerole:
        class: BdE\AdminBundle\Admin\AzureRoleAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "security", label: "Rôles Azure" }
        arguments:
            - ~
            - BdE\MainBundle\Entity\AzureRole
            - ~
        calls:
            - [ setTranslationDomain, [BdEAdminBundle]]