<?php

namespace Cva\GestionMembreBundle\Entity;

/**
 * PaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentRepository extends \Doctrine\ORM\EntityRepository
{
    public function findPaymentsForStudent(Etudiant $student){
        $q = $this->createQueryBuilder("p")->where("p.student=?1")->getQuery();
        $q->setParameter(1, $student);
        return $q->getResult();
    }

    public function countPaymentsForProduct(Produit $product){
        $q = $this->createQueryBuilder("p")->select("COUNT(p.id)")->where("p.product=?1")->getQuery();
        $q->setParameter(1, $product);
        return $q->getSingleScalarResult();
    }
}
