<?php

namespace Cva\GestionMembreBundle\Entity;

/**
 * PaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentRepository extends \Doctrine\ORM\EntityRepository
{
    public function findPaymentsForStudent(Etudiant $student){
        $q = $this->createQueryBuilder("p")->where("p.student=?1")->getQuery();
        $q->setParameter(1, $student);
        return $q->getResult();
    }

    public function countPaymentsForProduct(Produit $product){
        $q = $this->createQueryBuilder("p")->select("COUNT(p.id)")->where("p.product=?1")->getQuery();
        $q->setParameter(1, $product);
        return $q->getSingleScalarResult();
    }

    public function countMonthSales()
    {
        $lastDayOfMonth = new \DateTime("last day of today +23 hours +59 minutes +59 seconds");
        $startOfMonth = new \DateTime("first day of today");

        $query = $this->_em->createQuery(
            'SELECT COUNT(p)
					FROM  CvaGestionMembreBundle:Payment p
					WHERE p.date BETWEEN (?1) AND (?2)
					AND p.product IN (?3)')
            ->setParameter(1 , $startOfMonth)
            ->setParameter(2 , $lastDayOfMonth)
            ->setParameter(3 , $this->_em->getRepository("CvaGestionMembreBundle:Produit")->getCurrentVAIds());

        $nbVentes = $query->getSingleScalarResult();

        return $nbVentes;
    }

    public function countSalesByDepartment($departmentCode){

    }
}
