<?php

namespace Proxies\__CG__\Cva\GestionMembreBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Etudiant extends \Cva\GestionMembreBundle\Entity\Etudiant implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setFirstName($firstName)
    {
        $this->__load();
        return parent::setFirstName($firstName);
    }

    public function getFirstName()
    {
        $this->__load();
        return parent::getFirstName();
    }

    public function setNumEtudiant($numEtudiant)
    {
        $this->__load();
        return parent::setNumEtudiant($numEtudiant);
    }

    public function getNumEtudiant()
    {
        $this->__load();
        return parent::getNumEtudiant();
    }

    public function setBirthday($birthday)
    {
        $this->__load();
        return parent::setBirthday($birthday);
    }

    public function getBirthday()
    {
        $this->__load();
        return parent::getBirthday();
    }

    public function setMail($mail)
    {
        $this->__load();
        return parent::setMail($mail);
    }

    public function getMail()
    {
        $this->__load();
        return parent::getMail();
    }

    public function setTel($tel)
    {
        $this->__load();
        return parent::setTel($tel);
    }

    public function getTel()
    {
        $this->__load();
        return parent::getTel();
    }

    public function setCivilite($civilite)
    {
        $this->__load();
        return parent::setCivilite($civilite);
    }

    public function getCivilite()
    {
        $this->__load();
        return parent::getCivilite();
    }

    public function setPaiement(\Cva\GestionMembreBundle\Entity\Paiement $paiement = NULL)
    {
        $this->__load();
        return parent::setPaiement($paiement);
    }

    public function getPaiement()
    {
        $this->__load();
        return parent::getPaiement();
    }

    public function setRemarque($remarque)
    {
        $this->__load();
        return parent::setRemarque($remarque);
    }

    public function getRemarque()
    {
        $this->__load();
        return parent::getRemarque();
    }

    public function setAnnee($annee)
    {
        $this->__load();
        return parent::setAnnee($annee);
    }

    public function getAnnee()
    {
        $this->__load();
        return parent::getAnnee();
    }

    public function setDepartement($departement)
    {
        $this->__load();
        return parent::setDepartement($departement);
    }

    public function getDepartement()
    {
        $this->__load();
        return parent::getDepartement();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'firstName', 'annee', 'departement', 'numEtudiant', 'birthday', 'mail', 'tel', 'civilite', 'remarque');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}