bd_e_main:
    resource: "@BdEMainBundle/Resources/config/routing.yml"
    prefix:   /

wei:
    resource: "@BdEWeiBundle/Resources/config/routing.yml"
    prefix:   /wei

cva_gestion_membre:
    resource: "@CvaGestionMembreBundle/Resources/config/routing.yml"
    prefix:   /

login:
    pattern:  /login
    defaults: { _controller: CvaGestionMembreBundle:GestionMembre:login }

login_check:
    pattern:   /login_check
 
logout:
    pattern:   /logout
