security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm:           sha512
            encode_as_base64:    true
            iterations:          %password.iterations%
        BdE\MainBundle\Entity\User:
            algorithm:           sha512
            encode_as_base64:    true
            iterations:          %password.iterations%

    role_hierarchy:
        ROLE_USER:        ROLE_CONSULT
        ROLE_SOIREE:      ROLE_CONSULT
        ROLE_PERM:        ROLE_SOIREE
        ROLE_MODO:        ROLE_PERM
        ROLE_COWEI:       [ROLE_PERM, ROLE_EDIT_CONFIG]
        ROLE_ADMIN:       [ROLE_MODO, ROLE_COWEI, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_profiler|_wdt|css|js)
            security:  false
        main:
            pattern:   ^/
            anonymous: true
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
                always_use_default_target_path: true
                default_target_path: /asso/is_member
            oauth:
                resource_owners:
                    bde_azure:    "/login/check-azure"
                login_path:   /login
                use_forward:  false
                failure_path: /login
                oauth_user_provider:
                    service: bde.main.user_provider
            logout: true
            remember_me:
                key:      "%secret%"
                lifetime: 3600 # 1h en secondes
                path:     /
                domain:   ~

    access_control:
        - { path: ^/email, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/w, roles: ROLE_PERM }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/wei, roles: ROLE_COWEI }
        - { path: ^/config, roles: ROLE_EDIT_CONFIG }
        - { path: ^/adherent, roles: ROLE_SOIREE }
        - { path: ^/members, roles: ROLE_CONSULT }
        - { path: ^/anciens, roles: ROLE_SOIREE }
        - { path: ^/ajoutAdherent, roles: ROLE_SOIREE }
        - { path: ^/profil, roles: ROLE_USER }
        - { path: ^/asso, roles: ROLE_CONSULT}
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
