<?php

namespace BdE\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;
use Symfony\Component\Console\Output\OutputInterface;

/**
 * AzureRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AzureRoleRepository extends EntityRepository{

    public function getAllByGID(){
        /** @var AzureRole[] $roles */
        $roles = $this->findAll();
        $data = array();
        foreach($roles as $role){
            $data[$role->getAzureGid()] = $role;
        }
        return $data;
    }

}
