<?php

namespace BdE\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Console\Output\OutputInterface;

/**
 * ConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigRepository extends EntityRepository{

    /**
     * @var string[]
     */
    private $cachedConfig;

    /**
     * Get all config stored as a mapped array.
     * @return string[] The config values mapped with names.
     */
    public function getConfig(){
        if(!$this->cachedConfig){
            $all = $this->findAll();
            $config = array(
                "config.load_time" => strval(time())
            );
            /** @var Config $conf */
            foreach($all as $conf){
                $config[$conf->getName()] = $conf->getValue();
            }
            $this->cachedConfig = $config;
        }
        return $this->cachedConfig;
    }

}
