<?php

namespace BdE\MainBundle\Entity;
use Cva\GestionMembreBundle\Entity\Etudiant as Student;
use Cva\GestionMembreBundle\Entity\Produit as Product;
use Doctrine\ORM\EntityRepository;

/**
 * MailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailRepository extends EntityRepository
{
    /**
     * Find the most suitable mail for this student and product.
     * @param Student $student The student which will receive the mail
     * @param Product $product The product that just be bought by this student. This is used to be add to student
     *                          bought products for criteria to send the mail
     * @return Mail|null
     */
    public function getMail(Student $student, Product $product)
    {
        $mails = $this->createQueryBuilder("mail")->where("mail.active = true")
            ->orderBy("mail.priority","ASC")
            ->addOrderBy("mail.nbOfConditions", "DESC")
            ->addOrderBy("mail.forNewMembers", "ASC")
            ->getQuery()->getResult();
        $mail = null;
        /** @var Mail $m */
        foreach($mails as $m){
            if($m->canBeSentTo($student,array($product))){
                $mail = $m;
                break;
            }
        }
        if($mail){
            return $mail;
        }
        return null;
    }
}
