<?php

namespace BdE\WeiBundle\Entity;

/**
 * WaitingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WaitingRepository extends \Doctrine\ORM\EntityRepository
{
}
