<?php

namespace BdE\WeiBundle\Entity;
use Cva\GestionMembreBundle\Entity\Etudiant;
use Cva\GestionMembreBundle\Entity\Payment;
use Cva\GestionMembreBundle\Entity\Produit;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\UnexpectedResultException;

/**
 * WaitingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WaitingRepository extends EntityRepository
{
    public function nextTicket(Payment $produit, Etudiant $student){
        $qb = $this->createQueryBuilder('waiting')->select("MAX(waiting.rank)");
        $ticket = new Waiting();
        $ticket->setStudent($student);
        $ticket->setPayment($produit);
        try {
            $ticket->setRank($qb->getQuery()->getSingleScalarResult()+1);
        } catch(UnexpectedResultException $e){
            $ticket->setRank(1);
        }
        return $ticket;
    }
}
