
########################################################################################################################
####          WEI Routing file
## Ce fichier contient les routes nécessaire à la gestion d'un WEI sur Adhesion
#######################################################################################################################

bde_wei: # Main route, not used, should redirect to bde_wei_inscription_listeAttente
    pattern: /
    defaults: { _controller: BdEWeiBundle:Default:index }

#######################################
###    Gestion des bus

bde_wei_bus:
  resource: "@BdEWeiBundle/Controller/BusController.php"
  type: annotation
  prefix: /bus

#######################################
###    Gestion des Bungalows

bde_wei_bungalow:
  resource: "@BdEWeiBundle/Controller/BungalowController.php"
  type: annotation
  prefix: /bungalows

#######################################
###    Gestion des inscriptions

bde_wei_registration:
  resource: "@BdEWeiBundle/Controller/RegistrationController.php"
  type: annotation
  prefix: /registration
