parameters:
#    bd_e_wei.example.class: BdE\WeiBundle\Example

services:
  bde.wei.admin.bus:
        class: BdE\WeiBundle\Admin\BusAdmin
        tags:
            - { name: sonata.admin, manager_type: orm , group: "wei", label: "Bus"}
        arguments:
            - ~
            - BdE\WeiBundle\Entity\Bus
            - ~
        calls:
            - [ setTranslationDomain, [BdEWeiBundle]]

  bde.wei.admin.bungalow:
        class: BdE\WeiBundle\Admin\BungalowAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "wei", label: "Bungalow" }
        arguments:
            - ~
            - BdE\WeiBundle\Entity\Bungalow
            - ~
        calls:
            - [ setTranslationDomain, [BdEWeiBundle]]
