parameters:
#    bd_e_wei.example.class: BdE\WeiBundle\Example

services:
  bde.wei.paymentListener:
    class: BdE\WeiBundle\Listener\PaymentListener
    tags:
        - { name: doctrine.event_listener, event: prePersist }
        - { name: doctrine.event_listener, event: postPersist }
        - { name: doctrine.event_listener, event: preRemove }
    arguments: [@service_container]

  bde.wei.admin.bus:
    class: BdE\WeiBundle\Admin\BusAdmin
    tags:
        - { name: sonata.admin, manager_type: orm , group: "wei", label: "Bus"}
    arguments:
        - ~
        - BdE\WeiBundle\Entity\Bus
        - ~

  bde.wei.registration_management:
    class: BdE\WeiBundle\Entity\RegistrationManagement
    arguments: [@doctrine.orm.default_entity_manager]

  bde.wei.admin.bungalow:
    class: BdE\WeiBundle\Admin\BungalowAdmin
    tags:
        - { name: sonata.admin, manager_type: orm, group: "wei", label: "Bungalow" }
    arguments:
        - ~
        - BdE\WeiBundle\Entity\Bungalow
        - ~
