wei.nbMaxBizuths: 447
wei.dateWEI: "2014-09-27"
wei.produitPreInscritsWEI: 9
wei.produitInscriptionWEI: 10
wei.produitListeWEI: 15
wei.produitListePreWEI: 16
wei.produitRemboursementWEI: 11
wei.bungMixtes: true
cva.produitVA: "20,21,22"