parameters:
#    bd_e_main.example.class: BdE\MainBundle\Example

services:
#    bd_e_main.example:
#        class: %bd_e_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
