<?php

namespace Proxies\__CG__\Cva\GestionMembreBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Paiement extends \Cva\GestionMembreBundle\Entity\Paiement implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function addProduit(\Cva\GestionMembreBundle\Entity\Produit $produits)
    {
        $this->__load();
        return parent::addProduit($produits);
    }

    public function removeProduit(\Cva\GestionMembreBundle\Entity\Produit $produits)
    {
        $this->__load();
        return parent::removeProduit($produits);
    }

    public function getProduits()
    {
        $this->__load();
        return parent::getProduits();
    }

    public function setIdEtudiant(\Cva\GestionMembreBundle\Entity\Etudiant $idEtudiant)
    {
        $this->__load();
        return parent::setIdEtudiant($idEtudiant);
    }

    public function getIdEtudiant()
    {
        $this->__load();
        return parent::getIdEtudiant();
    }

    public function setDateAchat($dateAchat)
    {
        $this->__load();
        return parent::setDateAchat($dateAchat);
    }

    public function getDateAchat()
    {
        $this->__load();
        return parent::getDateAchat();
    }

    public function setUpdated()
    {
        $this->__load();
        return parent::setUpdated();
    }

    public function setMoyenPaiement($moyenPaiement)
    {
        $this->__load();
        return parent::setMoyenPaiement($moyenPaiement);
    }

    public function getMoyenPaiement()
    {
        $this->__load();
        return parent::getMoyenPaiement();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'dateAchat', 'moyenPaiement', 'idEtudiant', 'produits');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}