<?php

namespace Cva\GestionMembreBundle\Validator\Constraints;

use Symfony\Component\Validator\Constraint;

class ProductSell extends Constraint
{
    public $message = 'p1 et p2 ne peuvent pas être vendu ensembles.';

    public function validatedBy()
    {
        return "product_sell"; // TODO: Change the autogenerated stub
    }

}