#Bizuths
cva_gestion_membre_ajoutAdherent:
    pattern:  /ajoutAdherent
    defaults: { _controller: CvaGestionMembreBundle:GestionMembre:ajoutAdherent }

cva_gestion_membre_caca:
    pattern:  /
    defaults: { _controller: CvaGestionMembreBundle:GestionMembre:caca }

cva_gestion_membre_paiement:
    pattern:  /paiement
    defaults: { _controller: CvaGestionMembreBundle:GestionMembre:paiement }

cva_gestion_membre_editPaiement:
    pattern:  /editPaiement
    defaults: { _controller: CvaGestionMembreBundle:GestionMembre:editPaiement }

cva_gestion_membre_deletePaiement:
    pattern:  /deletePaiement
    defaults: { _controller: CvaGestionMembreBundle:GestionMembre:deletePaiement }

cva_gestion_membre_deleteAdherent:
    pattern:  /deleteAdherent
    defaults: { _controller: CvaGestionMembreBundle:GestionMembre:deleteAdherent }

cva_gestion_membre_adherent:
    pattern:  /adherent
    defaults: { _controller: CvaGestionMembreBundle:GestionMembre:adherent }

cva_gestion_membre_anciens:
    pattern:  /anciens
    defaults: { _controller: CvaGestionMembreBundle:GestionMembre:anciens }

cva_gestion_membre_admin:
    pattern:  /admin
    defaults: { _controller: CvaGestionMembreBundle:GestionMembre:admin }

cva_gestion_membre_voirDetails:
    pattern:  /voirDetails
    defaults: { _controller: CvaGestionMembreBundle:GestionMembre:voirDetails }

cva_gestion_membre_edit:
    pattern:  /editetudiant
    defaults: { _controller: CvaGestionMembreBundle:GestionMembre:editEtudiant }

cva_gestion_membre_editConfirm:
    pattern:  /editetudiantConfirm
    defaults: { _controller: CvaGestionMembreBundle:GestionMembre:editEtudiantConfirm }

#Zone Admin
cva_gestion_membre_addUser:
    pattern:  /admin/addUser
    defaults: { _controller: CvaGestionMembreBundle:GestionMembre:addUser }

cva_gestion_membre_stats:
    pattern:  /stats
    defaults: { _controller: CvaGestionMembreBundle:GestionMembre:stats }

cva_gestion_membre_modifUser:
    pattern:  /admin/modifUser
    defaults: { _controller: CvaGestionMembreBundle:GestionMembre:modifUser }

cva_gestion_membre_editUser:
    pattern:  /admin/editUser
    defaults: { _controller: CvaGestionMembreBundle:GestionMembre:editUser }

cva_gestion_membre_deleteUser:
    pattern:  /admin/deleteUser
    defaults: { _controller: CvaGestionMembreBundle:GestionMembre:deleteUser }

cva_gestion_membre_addProduit:
    pattern:  /admin/addProduit
    defaults: { _controller: CvaGestionMembreBundle:GestionMembre:addProduit }

cva_gestion_membre_editProduit:
    pattern:  /admin/editProduit
    defaults: { _controller: CvaGestionMembreBundle:GestionMembre:editProduit }

cva_gestion_membre_tableauProduits:
    pattern:  /admin/tableauProduits
    defaults: { _controller: CvaGestionMembreBundle:GestionMembre:tableauProduits }

cva_gestion_membre_deleteProduit:
    pattern:  /admin/deleteProduit
    defaults: { _controller: CvaGestionMembreBundle:GestionMembre:deleteProduit }

cva_gestion_membre_deleteAdherent:
    pattern:  /admin/deleteAdherent
    defaults: { _controller: CvaGestionMembreBundle:GestionMembre:deleteAdherent }

cva_gestion_membre_writeJSONGeneral:
    pattern:  /writeJSONGeneral
    defaults: { _controller: CvaGestionMembreBundle:GestionMembre:writeJSONGeneral }

#Autres
cva_gestion_membre_profil:
    pattern:  /profil
    defaults: { _controller: CvaGestionMembreBundle:GestionMembre:profil }

cva_gestion_membre_config:
    pattern:  /config
    defaults: { _controller: CvaGestionMembreBundle:GestionMembre:config }

cva_gestion_membre_isMember:
    pattern:  /api/is_member
    defaults: { _controller: CvaGestionMembreBundle:GestionMembre:is_member }

cva_gestion_membre_get:
    pattern:  /get
    defaults: { _controller: CvaGestionMembreBundle:GestionMembre:get }

cva_gestion_membre_exportCSV:
    pattern:  /exportCSV
    defaults: { _controller: CvaGestionMembreBundle:GestionMembre:exportCSV }

cva_gestion_membre_ajoutBus:
    pattern:  /ajoutBus
    defaults: { _controller: CvaGestionMembreBundle:GestionMembre:ajoutBus }

cva_gestion_membre_editBus:
    pattern:  /editBus
    defaults: { _controller: CvaGestionMembreBundle:GestionMembre:editBus }

cva_gestion_membre_deleteBus:
    pattern:  /deleteBus
    defaults: { _controller: CvaGestionMembreBundle:GestionMembre:deleteBus }

cva_gestion_membre_createMultipleBus:
    pattern:  /createMultipleBus
    defaults: { _controller: CvaGestionMembreBundle:GestionMembre:createMultipleBus }

cva_gestion_membre_ajoutBung:
    pattern:  /ajoutBung
    defaults: { _controller: CvaGestionMembreBundle:GestionMembre:ajoutBung }

cva_gestion_membre_editBung:
    pattern:  /editBung
    defaults: { _controller: CvaGestionMembreBundle:GestionMembre:editBung }

cva_gestion_membre_deleteBung:
    pattern:  /deleteBung
    defaults: { _controller: CvaGestionMembreBundle:GestionMembre:deleteBung }

cva_gestion_membre_createMultipleBung:
    pattern:  /createMultipleBung
    defaults: { _controller: CvaGestionMembreBundle:GestionMembre:createMultipleBung }

cva_gestion_membre_writeJSONWEI:
    pattern:  /writeJSONWEI
    defaults: { _controller: CvaGestionMembreBundle:GestionMembre:writeJSONWEI }

#Zone CoWEI
cva_gestion_membre_ajoutBizuthWEI:
    pattern:  /wei/ajoutBizuthWEI
    defaults: { _controller: CvaGestionMembreBundle:GestionMembre:ajoutBizuthWEI }

cva_gestion_membre_préInscrits:
    pattern:  /wei/preInscrits
    defaults: { _controller: CvaGestionMembreBundle:GestionMembre:preInscrits }

cva_gestion_membre_rechercheBizuthWEI:
    pattern:  /wei/partants
    defaults: { _controller: CvaGestionMembreBundle:GestionMembre:rechercheBizuthWEI }

cva_gestion_membre_listeAttente:
    pattern:  /wei/listeAttente
    defaults: { _controller: CvaGestionMembreBundle:GestionMembre:listeAttente }

cva_gestion_membre_listeAttentePre:
    pattern:  /wei/listeAttentePre
    defaults: { _controller: CvaGestionMembreBundle:GestionMembre:listeAttentePre }

cva_gestion_membre_remboursements:
    pattern:  /wei/remboursements
    defaults: { _controller: CvaGestionMembreBundle:GestionMembre:remboursements }

cva_gestion_membre_remplacer:
    pattern:  /wei/remplacer
    defaults: { _controller: CvaGestionMembreBundle:GestionMembre:remplacer }

cva_gestion_membre_editBizuthWEI:
    pattern:  /wei/editetudiant
    defaults: { _controller: CvaGestionMembreBundle:GestionMembre:editEtudiant }    

cva_gestion_membre_paiementBizuthWEI:
    pattern:  /wei/paiement
    defaults: { _controller: CvaGestionMembreBundle:GestionMembre:paiement }

cva_gestion_membre_ajoutDetailsWEI:
    pattern:  /wei/ajoutDetailsWEI
    defaults: { _controller: CvaGestionMembreBundle:GestionMembre:ajoutDetailsWEI }

cva_gestion_membre_voirDetails2:
    pattern:  /wei/voirDetails
    defaults: { _controller: CvaGestionMembreBundle:GestionMembre:voirDetails }

cva_gestion_membre_clearWEI:
    pattern:  /wei/clearWEI
    defaults: { _controller: CvaGestionMembreBundle:GestionMembre:clearWEI }

