services:
    cva_gestion_membre:
        class: Cva\GestionMembreBundle\Service\ServiceMembre
        arguments:
          em: "@doctrine.orm.entity_manager"
    login_listener:
        class: 'Cva\GestionMembreBundle\EventListener\LoginListener'
        arguments: ['@security.context', '@session']
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login' }

    cva.gestion_membre.stats:
      class: Cva\GestionMembreBundle\Service\StatsService
      arguments: [@doctrine.orm.entity_manager]

    cva.gestion_membre.products:
      class: Cva\GestionMembreBundle\Service\Products
      arguments: [@service_container]

    cva.gestion_membre.product_sell_validator:
      class: Cva\GestionMembreBundle\Validator\Constraints\ProductSellValidator
      arguments: [@cva.gestion_membre.products]
      tags:
        - { name: validator.constraint_validator, alias: product_sell }

    cva.gestion_membre.admin.students:
          class: Cva\GestionMembreBundle\Admin\EtudiantAdmin
          tags:
              - { name: sonata.admin, manager_type: orm, group: "cva", label: "Members" }
          arguments:
              - ~
              - Cva\GestionMembreBundle\Entity\Etudiant
              - ~

    cva.gestion_membre.admin.produits:
          class: Cva\GestionMembreBundle\Admin\ProduitAdmin
          tags:
              - { name: sonata.admin, manager_type: orm, group: "cva", label: "Products" }
          arguments:
              - ~
              - Cva\GestionMembreBundle\Entity\Produit
              - ~